### ISSUE TITLE
Initialization problem for dev build on maine-region

### ISSUE THREAD

**Issue by erikmartin88** [CoastalResilienceNetwork/future_habitat_v2#1]
Hi Jacob @lesserj ,

I'm getting ready to launch the new barrier-prioritization-v3 app on maine-region.  I did a test build on my local machine and the future-habitat-v2 app isn't working, so I stopped short of installing the new build on the CR Dev server.  The build installs OK, but the future-habitat-v2 app is blank with the following error in the init function:
![image](https://user-images.githubusercontent.com/11949705/37798712-f1449876-2df3-11e8-86c4-1f5947650ff0.png)

I dug into main.js line 76 and it looks like there's some region.json values that it's looking for:
![image](https://user-images.githubusercontent.com/11949705/37798793-2952850c-2df4-11e8-89f8-c70408c83139.png)

I didn't see where there should be coming from.  Looked at the north carolina region, too, and didn't see.  Any insight?  I'd like to build on Dev tomorrow so folks can test it before going to Prod next week.  

Many thanks!
-Erik

**Comment by lesserj** [comment]
We made a bunch of changes for North Carolina.  I just pushed up to dev the updated region.json file for Maine.  Go ahead and try and deploy dev again.  Maine should work.

**Comment by erikmartin88** [comment]
Ok, great thanks, Jacob!

**Comment by erikmartin88** [comment]
Wanted to let you know that this worked and I've rebuilt Maine dev with no problems.  Looks like the future-habitat-v2 changes are still only on the development branch, so I don't anticipate this issue when I rebuild the maine-region Prod site next week, but if I've got that wrong let me know. Thanks
-Erik
